#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Plugin.SalaAula.Video;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Video/Views/Video/Index.cshtml")]
    public partial class _Areas_Video_Views_Video_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Video_Views_Video_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Areas\Video\Views\Video\Index.cshtml"
  
    ViewBag.Title = "Plugin Vídeo";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("headers", () => {

WriteLiteral("\r\n    <style>\r\n        .modal-dialog {\r\n            width: 75%;\r\n            marg" +
"in: 50px auto;\r\n            padding: 0;\r\n        }\r\n\r\n        .modal-content {\r\n" +
"            border-radius: 0;\r\n        }\r\n    </style>\r\n");

});

WriteLiteral("\r\n<div");

WriteLiteral(" class=\"darwinenem\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"wrapper wrapper-content animated fadeInRight\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-xs-12 col-md-12 col-sm-12 col-lg-12\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"text-center title-gray\"");

WriteLiteral(">Pesquise pelo assunto desejado?</div>\r\n            <div");

WriteLiteral(" class=\"marginbottom30\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"busca-video\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"form-group row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-xs-10\"");

WriteLiteral("><input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" placeholder=\"Buscar pelo assunto desejado\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" name=\"top-search\"");

WriteLiteral(" id=\"top-search\"");

WriteLiteral("></div>\r\n                        <div");

WriteLiteral(" class=\"col-xs-2\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-search icone\"");

WriteLiteral(" style=\"cursor: pointer;\"");

WriteLiteral("></i></div>\r\n                    </div>\r\n                </div>\r\n            </di" +
"v>\r\n        </div>\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
